push: lock repo before calling createmarkers
Previously, when devel.all-warnings is set to True, hg subversion will crash
when pushing with the error:

  ProgrammingError: transaction requires locking

Tracking that down, that is because "createmarkers" was called without
locking.

A comprehensive test was added to run test_push_command with obsstore turned
on to cover the code paths.

--HG--
extra : histedit_source : 2f9f31a94bb61019cfc00a36f399d44ea5cc3df9